#!/bin/bash
# Author: Valeriy Kornienko <vikornienko76@gmail.com>
# Telegraf with CommonJS. Simple project structure.
# Copy this file into your bot projects directory and run it.
# Step 1: ask user for the project name
echo "Prepare the telegram bot token in advance - you will need to add it when running this script."

echo "Enter the project name: " 
read -r project_name

# echo "Enter directory for project: "
# read -r directory_name

echo "Enter author name: "
read -r author_name

echo "Enter description: "
read -r description

# Step 2: navigate to projects directoty and create directory (if not exist) and project folder
if ! [ -d ./"$project_name" ] 
then
echo "Directory $project_name does not exist but will be created."
mkdir "$project_name"
fi
cd ./"$project_name" || exit && echo "Exit from string 25."
# Step 3: Create a package.json file. Add the project name to it.
cat <<EOF >package.json
{
  "name": "$project_name",
  "version": "1.0.0",
  "description": "$description",
  "main": "bot.js",
  "scripts": {
    "start": "nodemon ./src/bot.js",
    "start:debug": "nodemon --inspect bot.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "node.js",
    "telegraf.js"
  ],
  "author": "$author_name",
  "license": "ISC",
  "dependencies": {
    "dotenv": "^16.4.5",
    "telegraf": "^4.16.3"
  },
  "devDependencies": {
    "nodemon": "^3.1.7"
  }
}
EOF
# Step 4: Create a README.md file. Add the project name to it.
cat <<EOF >README.md
# $project_name

A repository for self-study on writing telegram bots on node.js.

$description
To create the bot in this repository, the following were used:
- telegraf node.js library;
- dotenv library for storing variables in the .env file;
- nodemon for automatically applying changes to files.
EOF
# Step 5: Request a bot token.
echo "Enter bot token: "
read -r token
# Step 6: Creating the .env file. Saving the bot token in it.
cat <<EOF >.env
BOT_TOKEN="$token"
EOF
# Step 7: Creating the .env.example file.
cat <<EOF >.env.example
BOT_TOKEN="insert_your_token_here"
EOF
# Step 8: Createing the .gitignore file.
cat <<EOF >.gitignore
# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*
.pnpm-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# Snowpack dependency directory (https://snowpack.dev/)
web_modules/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional stylelint cache
.stylelintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variable files
.env
.env.development.local
.env.test.local
.env.production.local
.env.local

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next
out

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and not Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public

# vuepress build output
.vuepress/dist

# vuepress v2.x temp and cache directory
.temp
.cache

# Docusaurus cache and generated files
.docusaurus

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# yarn v2
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*
EOF
# Step 9: Create a bot.js file. Adding code for first run.
mkdir src && cd ./src || exit && echo "Exit from string 210."
cat <<EOF >bot.js
require('dotenv').config()
const { Telegraf } = require('telegraf')
const { message } = require('telegraf/filters')

const bot = new Telegraf(process.env.BOT_TOKEN)
bot.start((ctx) => ctx.reply('Welcome'))
bot.help((ctx) => ctx.reply('Send me a sticker'))
bot.on(message('sticker'), (ctx) => ctx.reply('👍'))
bot.hears('hi', (ctx) => ctx.reply('Hey there'))
bot.launch()

// Enable graceful stop
process.once('SIGINT', () => bot.stop('SIGINT'))
process.once('SIGTERM', () => bot.stop('SIGTERM'))
EOF
cd ..
# Step 10: Install dependencies from package.json file.
npm i
# Step 11: Start VSCode in project directory.
code .